name: Checkout Repository Example

on: [push]

jobs:
  explore_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: List repository files
        run: ls -la

      - name: Display README file
        run: cat README.md
